[package]
name = "hulu_sami"
version = "0.1.0"
authors = ["Musee Ullah <lae@lae.is>"]

[dependencies]
rustc-serialize = '*'
lazy_static = '*'
xml-rs = '*'
openssl = '*'
encoding = '*'
hyper = '*'
url = { git = "https://github.com/servo/rust-url" }
